Cleanup instances on shutdown
borgstrom/offspring pull request #3
Opened 2019-10-22 14:02 UTC by jeffglover

In the context of, https://github.com/NerdWalletOSS/kinesis-python, if multiple SubprocessLoop instances are created and and shutdown during a long running process eventually you'll hit `OSError: [Errno 24] Too many open files`. This ensures the instances are cleaned up while running.

2021-02-01 14:10 UTC, borgstrom requested changes
Can you please also add test that asserts the instances getting removed?

2021-02-01 14:12 UTC, borgstrom reviewed
Sorry, I tried to add this comment to my last review but I guess I didn't save it correctly...

2021-02-01 14:12 UTC, borgstrom commented on src/offspring/process.py
> +                self._INSTANCES.remove(self)
`_INSTANCES` is a class attribute, so this should be:

```python
while self in self.__class__._INSTANCES:
    self.__class__._INSTANCES.remove(self)
```

2021-04-19 05:06 UTC, ngsharsha commented
@borgstrom can this be merged ?

2021-04-19 12:15 UTC, borgstrom commented
@ngsharsha - Not yet. My comment about `_INSTANCES` being a class attribute still needs to be addressed and this still needs tests.

We don't run into this situation in our use of kinesis-python so I haven't had a driving force to complete this. If you want to add tests and address my comment in a new PR I would be happy to review/merge.

2021-04-19 15:36 UTC, jeffglover commented
This totally fell off my radar a long time ago. Since AWS kinesis can now trigger lambdas, I don't really have a need for it. I'll try to get to it this week so at least the fix gets in. I'm not opposed to someone taking it over though.

2023-12-03 22:48 UTC, closed without merging